#!/bin/bash
# Above is important. Or else read doesn't work (in zsh)

figlet -c "Docker  &  K8s  Quiz"
read -p ""
cowsay -f apt "Cloud Native Technologies"
read -p ""
cowsay -f bud-frogs "Docker Images"
read -p ""
cowsay -f default "Docker build and Multi-stage Builds"
read -p ""
cowsay -f bunny "Docker Registry"
read -p ""
cowsay -f daemon "How to connect to a shell inside a running container?"
read -p ""
echo "See docker exec"
read -p ""
cowsay -f moose "What does a K8s cluster contain?"
read -p ""
cowsay -f hellokitty "Api server"
read -p ""
cowsay -f pony-smaller "Pod"
read -p ""
cowsay -f sheep "Namespace"
read -p ""
cowsay -f suse "Labels and Annotations"
read -p ""
cowsay -f duck "Replica Sets"
read -p ""
cowsay -f default "Deployment"
read -p ""
cowsay -f cower "Service"
read -p ""
cowsay -f tux "Done.."

