apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx-something
    run: demo
  name: demo
spec:
  containers:
  - image: nginx
    name: demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
